apiVersion: v1
kind: Service
metadata:
  # Change this back to the original helper name
  name: {{ include "person-service-rust.fullname" . }} 
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    # Change this back too
    {{- include "person-service-rust.selectorLabels" . | nindent 4 }}