apiVersion: v1
kind: Service
metadata:
  name: {{ include "person-service-rust-develop" . }}
spec:
  type: ClusterIP
  ports:
    - port: 80          # The "Entry Door" of the Service
      targetPort: 3000  # The "Exit Door" (Must match your Rust code!)
      protocol: TCP
      name: http
  selector:
    {{- include "person-service-rust-develop.selectorLabels" . | nindent 4 }}